volumes:
  postgres_data: {}

services:
  db:
    image: postgres:15.2-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: veri_id_user
      POSTGRES_PASSWORD: veri_id_password
      POSTGRES_DB: veri_id_development
      TZ: Asia/Tokyo
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
